test: othello_test.c
	gcc -o othello_test othello_test.c

server: othello_process_server.c
	gcc -o othello_process_server othello_process_server.c

client: othello_process_client.c
	gcc -o othello_process_client othello_process_client.c

all: server client
