CFLAGS = -O2
EXEC = ProcNonShareTest ProcShareTest ProcShareTest2 ProcShareTest3 ProcShareTest4 ProcShareSem ProcSemTest ProcMsgTestPwait ProcMsgTestCwait ProcMsgTestCwait2 ProcMsgTestCwait3 ProdCons


all: $(EXEC)

clean:
	rm -f $(EXEC) ProcMsgTestCwait3 *.o *.s *~
